// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/youngsun/Projects/ReactNative/StockManagement/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/youngsun/Projects/ReactNative/StockManagement/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('/Users/youngsun/Projects/ReactNative/StockManagement/index.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('StockManagement', appParameters);
});